"""users table

Revision ID: 85bd232dacc9
Revises: 
Create Date: 2019-10-28 03:22:00.825127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85bd232dacc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_table('schools')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('ATS_CODE', sa.TEXT(), nullable=True),
    sa.Column('BORO', sa.TEXT(), nullable=True),
    sa.Column('BORONUM', sa.TEXT(), nullable=True),
    sa.Column('LOC_CODE', sa.TEXT(), nullable=True),
    sa.Column('SCHOOLNAME', sa.TEXT(), nullable=True),
    sa.Column('SCH_TYPE', sa.TEXT(), nullable=True),
    sa.Column('MANAGED_BY', sa.TEXT(), nullable=True),
    sa.Column('GEO_DISTRI', sa.TEXT(), nullable=True),
    sa.Column('ADMIN_DIST', sa.TEXT(), nullable=True),
    sa.Column('ADDRESS', sa.TEXT(), nullable=True),
    sa.Column('STATE_CODE', sa.TEXT(), nullable=True),
    sa.Column('ZIP', sa.TEXT(), nullable=True),
    sa.Column('PRINCIPAL', sa.TEXT(), nullable=True),
    sa.Column('PRIN_PH', sa.TEXT(), nullable=True),
    sa.Column('FAX', sa.TEXT(), nullable=True),
    sa.Column('GRADES', sa.TEXT(), nullable=True),
    sa.Column('block', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('coordinates', sa.TEXT(), nullable=True),
    sa.Column('county_fips', sa.TEXT(), nullable=True),
    sa.Column('geocoded_address', sa.TEXT(), nullable=True),
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('is_exact', sa.TEXT(), nullable=True),
    sa.Column('is_match', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.TEXT(), nullable=True),
    sa.Column('longitude', sa.TEXT(), nullable=True),
    sa.Column('returned_address', sa.TEXT(), nullable=True),
    sa.Column('side', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('state_fips', sa.TEXT(), nullable=True),
    sa.Column('tiger_line', sa.TEXT(), nullable=True),
    sa.Column('tract', sa.TEXT(), nullable=True)
    )
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
